import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import './globalStyles/normalize.css'
import './globalStyles/globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Providers } from '@/components/elements/Auth/next_auth_providers'
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await auth()
	return (
		<SessionProvider session={session}>
			<html lang='en' suppressHydrationWarning>
				<body>
					{children}
					<Toaster reverseOrder={false} />
				</body>
			</html>
		</SessionProvider>
	)
}
